from pathlib import Path

path=Path('index.html')
s=path.read_text(encoding='utf-8')

def rep(old,new):
    global s
    if old not in s:
        raise SystemExit('Expected text not found: '+old[:140])
    s=s.replace(old,new,1)

rep(':root{--bg:#f7f3ec;--panel:#fffdf9;--ink:#302a25;--muted:#7b736b;--line:#ddd5ca;--accent:#75667b;--ok:#6f8a6f;--warn:#a77734;--danger:#9b4f47}',':root{--bg:#f7f3ec;--panel:#fffdf9;--ink:#302a25;--muted:#7b736b;--line:#ddd5ca;--accent:#75667b;--ok:#6f8a6f;--warn:#a77734;--danger:#9b4f47;--poem-font:Georgia,serif;--poem-size:25px;--poem-weight:400}')
rep('.editor{min-height:480px;padding:38px 54px;font-size:25px;line-height:1.7;outline:none;white-space:pre-wrap}', '.editor{min-height:480px;padding:38px 54px;font-family:var(--poem-font);font-size:var(--poem-size);font-weight:var(--poem-weight);line-height:1.7;outline:none;white-space:pre-wrap}')
rep('.tools{display:flex;gap:4px}.tools button{width:38px;height:38px;border:1px solid var(--line);background:#fff;border-radius:7px}', '.tools{display:flex;gap:4px}.tools button{width:38px;height:38px;border:1px solid var(--line);background:#fff;border-radius:7px}.tools #textBtn{width:auto;padding:0 10px;font:12px Arial,sans-serif}')
rep('.vb{white-space:pre-wrap;margin-top:9px;line-height:1.5}', '.vb{white-space:pre-wrap;margin-top:9px;line-height:1.5;font-family:var(--poem-font);font-size:calc(var(--poem-size)*.76);font-weight:var(--poem-weight)}')
rep('.newPoemNote{border-left:3px solid #cfc4d2;padding-left:12px!important;margin-top:4px!important}', '.newPoemNote{border-left:3px solid #cfc4d2;padding-left:12px!important;margin-top:4px!important}.textPrefs{display:grid;grid-template-columns:1fr 1fr;gap:14px}.textPref label{display:block;font:700 12px Arial,sans-serif;color:var(--muted);margin:0 0 6px}.textPref select{width:100%;border:1px solid var(--line);background:#fffdf9;padding:11px;border-radius:8px;color:var(--ink)}.textSample{margin-top:18px;padding:18px;border:1px solid var(--line);border-radius:9px;background:#fffdf9;font-family:var(--poem-font);font-size:var(--poem-size);font-weight:var(--poem-weight);line-height:1.5}')
rep('.compareGrid{grid-template-columns:1fr}}', '.compareGrid,.textPrefs{grid-template-columns:1fr}}')
rep('<div class="tools"><button data-cmd="italic" title="Italic"><i>I</i></button>', '<div class="tools"><button id="textBtn" title="Poem font and size">Text</button><button data-cmd="italic" title="Italic"><i>I</i></button>')
rep('<dialog id="updateDraftDialog" class="appDialog">', '<dialog id="textDialog" class="appDialog"><div class="dialogInner"><h2>Poem text</h2><p>Choose how poems appear while you write, review saved drafts, and compare versions.</p><div class="textPrefs"><div class="textPref"><label for="sizeSelect">Size</label><select id="sizeSelect"><option value="small">Small</option><option value="medium">Medium</option><option value="large">Large</option></select></div><div class="textPref"><label for="fontSelect">Font</label><select id="fontSelect"><option value="times">Times New Roman</option><option value="garamond">Garamond</option><option value="georgia">Georgia</option><option value="baskerville">Baskerville</option><option value="helvetica">Helvetica Neue Light</option></select></div></div><div class="textSample" id="textSample">A line of poetry, just to see.</div><div class="dialogActions"><button class="btn primary" id="textDone" type="button">Done</button></div></div></dialog>\n<dialog id="updateDraftDialog" class="appDialog">')
rep("function loadUI(){try{return Object.assign({leftOpen:true,notesOpen:false},JSON.parse(localStorage.getItem(UIKEY)||'{}'))}catch{return{leftOpen:true,notesOpen:false}}}", "function loadUI(){try{return Object.assign({leftOpen:true,notesOpen:false,poemSize:'medium',poemFont:'georgia'},JSON.parse(localStorage.getItem(UIKEY)||'{}'))}catch{return{leftOpen:true,notesOpen:false,poemSize:'medium',poemFont:'georgia'}}}")
rep("function saveUI(){localStorage.setItem(UIKEY,JSON.stringify(ui));applyPanels()}", "const FONT_MAP={times:'\\\"Times New Roman\\\",Times,serif',garamond:'Garamond,\\\"Adobe Garamond Pro\\\",\\\"EB Garamond\\\",serif',georgia:'Georgia,serif',baskerville:'Baskerville,\\\"Baskerville Old Face\\\",serif',helvetica:'\\\"Helvetica Neue\\\",Helvetica,Arial,sans-serif'},SIZE_MAP={small:'19px',medium:'25px',large:'31px'};\nfunction applyTextPrefs(){if(!FONT_MAP[ui.poemFont])ui.poemFont='georgia';if(!SIZE_MAP[ui.poemSize])ui.poemSize='medium';const root=document.documentElement;root.style.setProperty('--poem-font',FONT_MAP[ui.poemFont]);root.style.setProperty('--poem-size',SIZE_MAP[ui.poemSize]);root.style.setProperty('--poem-weight',ui.poemFont==='helvetica'?'300':'400');$('sizeSelect').value=ui.poemSize;$('fontSelect').value=ui.poemFont}\nfunction saveUI(){localStorage.setItem(UIKEY,JSON.stringify(ui));applyPanels();applyTextPrefs()}")
rep("$('leftToggle').onclick=()=>{ui.leftOpen=!ui.leftOpen;saveUI()};$('notesToggle').onclick=()=>{ui.notesOpen=!ui.notesOpen;saveUI()};$('closeNotes').onclick=()=>{ui.notesOpen=false;saveUI()};window.addEventListener('resize',applyPanels);", "$('leftToggle').onclick=()=>{ui.leftOpen=!ui.leftOpen;saveUI()};$('notesToggle').onclick=()=>{ui.notesOpen=!ui.notesOpen;saveUI()};$('closeNotes').onclick=()=>{ui.notesOpen=false;saveUI()};$('textBtn').onclick=()=>{$('sizeSelect').value=ui.poemSize;$('fontSelect').value=ui.poemFont;$('textDialog').showModal()};$('sizeSelect').onchange=e=>{ui.poemSize=e.target.value;saveUI()};$('fontSelect').onchange=e=>{ui.poemFont=e.target.value;saveUI()};$('textDone').onclick=()=>$('textDialog').close();$('textDialog').addEventListener('click',e=>{if(e.target===$('textDialog'))$('textDialog').close()});window.addEventListener('resize',applyPanels);")
old="function openComparison(leftIndex,rightIndex){const p=active(),a=p.versions[leftIndex],b=p.versions[rightIndex];if(!a||!b)return;const w=open('','_blank');if(!w){alert('Chrome blocked the comparison window. Please allow pop-ups for Revision Room.');return}const leftLabel='Draft '+(leftIndex+1),rightLabel='Draft '+(rightIndex+1);w.document.write('<title>'+esc(p.title)+' — compare</title><style>body{font-family:Georgia;background:#f7f3ec;color:#302a25;margin:30px}header{margin-bottom:22px}header h1{margin:0 0 5px}header p{margin:0;color:#7b736b;font-family:Arial,sans-serif}main{display:grid;grid-template-columns:1fr 1fr;gap:20px}.pane{min-width:0}.v{background:white;border:1px solid #ddd5ca;border-radius:10px;padding:22px;white-space:pre-wrap;line-height:1.6;min-height:60vh}.stamp{color:#7b736b;font:12px Arial,sans-serif;margin:-7px 0 10px}@media(max-width:760px){main{grid-template-columns:1fr}}</style><header><h1>'+esc(p.title)+'</h1><p>'+leftLabel+' compared with '+rightLabel+'</p></header><main><section class=pane><h3>'+leftLabel+'</h3><div class=stamp>'+esc(new Date(a.savedAt).toLocaleString())+'</div><div class=v>'+a.html+'</div></section><section class=pane><h3>'+rightLabel+'</h3><div class=stamp>'+esc(new Date(b.savedAt).toLocaleString())+'</div><div class=v>'+b.html+'</div></section></main>');w.document.close()}"
new="function openComparison(leftIndex,rightIndex){const p=active(),a=p.versions[leftIndex],b=p.versions[rightIndex];if(!a||!b)return;const w=open('','_blank');if(!w){alert('Chrome blocked the comparison window. Please allow pop-ups for Revision Room.');return}const leftLabel='Draft '+(leftIndex+1),rightLabel='Draft '+(rightIndex+1),poemFont=FONT_MAP[ui.poemFont]||FONT_MAP.georgia,poemSize=SIZE_MAP[ui.poemSize]||SIZE_MAP.medium,poemWeight=ui.poemFont==='helvetica'?'300':'400';w.document.write('<title>'+esc(p.title)+' — compare</title><style>body{font-family:Georgia;background:#f7f3ec;color:#302a25;margin:30px}header{margin-bottom:22px}header h1{margin:0 0 5px}header p{margin:0;color:#7b736b;font-family:Arial,sans-serif}main{display:grid;grid-template-columns:1fr 1fr;gap:20px}.pane{min-width:0}.v{background:white;border:1px solid #ddd5ca;border-radius:10px;padding:22px;white-space:pre-wrap;line-height:1.6;min-height:60vh;font-family:'+poemFont+';font-size:'+poemSize+';font-weight:'+poemWeight+'}.stamp{color:#7b736b;font:12px Arial,sans-serif;margin:-7px 0 10px}@media(max-width:760px){main{grid-template-columns:1fr}}</style><header><h1>'+esc(p.title)+'</h1><p>'+leftLabel+' compared with '+rightLabel+'</p></header><main><section class=pane><h3>'+leftLabel+'</h3><div class=stamp>'+esc(new Date(a.savedAt).toLocaleString())+'</div><div class=v>'+a.html+'</div></section><section class=pane><h3>'+rightLabel+'</h3><div class=stamp>'+esc(new Date(b.savedAt).toLocaleString())+'</div><div class=v>'+b.html+'</div></section></main>');w.document.close()}"
rep(old,new)
rep('applyPanels();render();(async()=>{','applyPanels();applyTextPrefs();render();(async()=>{')
for needle in ['id="textBtn"','id="textDialog"','FONT_MAP','Helvetica Neue Light','applyTextPrefs()']:
    if needle not in s: raise SystemExit('Missing result: '+needle)
path.write_text(s,encoding='utf-8')
print('Patched poem text options')